- components/MainNav.tsx
- components/OrganizationCard.tsx
- models/Lark.ts
- models/Organization.ts
- package.json
- pages/api/lark/file/[id].ts
- pages/api/lark/index.ts
- pages/api/organization.ts
- pages/organization/index.tsx
- pnpm-lock.yaml
> [add] Organization Filter

- components/OrganizationCard.tsx
- package.json
- pnpm-lock.yaml
1. [add] WeChat QRCode of Organization Card (fix #55)
2. [optimize] Summary Scrolling of Organization Card (fix #48)
> [add] WeChat QRCode of Organization Card

- components/ChinaMap.tsx
- components/OrganizationCard.tsx
- components/utility.ts
- models/Meta.ts
- models/Organization.ts
- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/api/organization/index.ts
- pages/api/organization/statistic.ts
- pages/organization/index.tsx
- pnpm-lock.yaml
1. [refactor] replace AMap with OpenStreetMap to break limitation (fix #52)
2. [add] Meta model & Organization Statistic API
3. [fix] WeChat QRCode generation
4. [optimize] some UI details
> [refactor] replace AMap with OpenStreetMap to break limitation

- components/CityStatisticMap.tsx
- components/OrganizationCard.tsx
- models/Activity.ts
- models/Group.ts
- models/Lark.ts
- models/Organization.ts
- next.config.js
- package.json
- pages/api/activity/statistic.ts
- pages/api/group/index.ts
- pages/api/lark/file/[id].ts
- pages/api/organization/statistic.ts
- pages/index.tsx
- pages/organization/index.tsx
- pnpm-lock.yaml
1. [add] Activity map of Home page based on City Statistic Map component & Activity Statistic API
2. [add] Project list of Home page based on Group API & model
3. [fix] some UI detail & webpack building bugs
> [add] Activity map & Project list of Home page

- components/OrganizationCharts.tsx
- components/TreeChart.tsx
- components/data.ts
- models/Group.ts
- models/Lark.ts
- package.json
- pages/_app.tsx
- pages/api/group/index.ts
- pages/api/organization/index.ts
- pages/department/index.tsx
- pages/index.tsx
- pnpm-lock.yaml
1. [add] Department page based on Tree Chart component
2. [refactor] List models support Static Render
> [add] Department page based on Tree Chart component

- components/Organization/Card.tsx
- components/Organization/Charts.tsx
- components/Organization/LandScape.tsx
- models/Base.ts
- models/Organization.ts
- package.json
- pages/index.tsx
- pages/organization/cooperation.tsx
- pages/organization/index.tsx
- pages/organization/landscape.tsx
- pnpm-lock.yaml
> [add] Organization Landscape page

- .env.development
- .env.production
- components/Activity/Agenda/Card.tsx
- components/Activity/Card.tsx
- components/Activity/List.tsx
- components/Article/List.tsx
- components/MainNav.tsx
- models/Activity.ts
- models/Agenda.ts
- models/Organization.ts
- package.json
- pages/activity/[id]/index.tsx
- pages/activity/index.tsx
- pages/api/activity/index.ts
- pages/api/article/index.ts
- pages/api/base.ts
- pages/api/lark/bitable/v1/[...slug].ts
- pages/api/lark/core.ts
- pages/article/[id]/index.tsx
- pages/article/index.tsx
- pages/index.tsx
- pages/members/index.tsx
- pages/organization/cooperation.tsx
- pages/search/index.tsx
- pnpm-lock.yaml
1. [add] Agenda model & Activity Detail page (closes #90)
2. [add] Agenda Card component
3. [add] Lark proxy API
4. [fix] Server-side State Racing & Nav Bar auto-collapsing
5. [fix] Image & Layout of Cooperation page
6. [optimize] some UI details
> [add] Agenda model & Activity Detail page

- models/Activity.ts
- next.config.js
- package.json
- pnpm-lock.yaml
1. [optimize] rewrite Fallback paths to GitHub pages (closes #42)
2. [optimize] simplify Cross Database reference
> [optimize] rewrite Fallback paths to GitHub pages

- pages/license-tool.tsx
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
> Fix: step error

- components/Article/Card.tsx
> [optimize] update article aspect ratio

- components/Activity/Agenda/Card.tsx
- models/Agenda.ts
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pnpm-lock.yaml
Checklist（清单）:
Closes #91
Fixes #109
> agenda detail page

- components/Activity/Agenda/People.tsx
- models/Agenda.ts
- models/System.ts
- package.json
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/agenda/[agendaId]/invitation.module.less
- pages/activity/[id]/agenda/[agendaId]/invitation.tsx
- pages/api/lark/core.ts
- pnpm-lock.yaml
1. [add] Agenda People component & Normalize Text Array method
2. [refactor] Agenda Detail page (fix #91)
> [add] Agenda People component & Normalize Text Array method

- components/Activity/Agenda/Card.tsx
- components/Activity/Agenda/Toolbar.tsx
- package.json
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/index.tsx
- pnpm-lock.yaml
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
closes kaiyuanshe/COSCon-2020-Apache-Roadshow---China#8
> [add] Agenda Toolbar component with iCalendar support

- components/Activity/Agenda/Card.tsx
- models/Activity.ts
- models/Agenda.ts
- package.json
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/agenda/[agendaId]/invitation.tsx
- pages/activity/[id]/index.tsx
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
1. [add] Form links & Agenda Type badges of Activity pages
2. [optimize] Invitation Card resizing & other Logic details
> [add] Form links & Agenda Type badges of Activity pages

- components/Activity/Agenda/Card.tsx
> [feat] add Image Carousel for Activity Agenda Card

- components/Activity/People.tsx
> [feat] add default avatar for people component

- components/Activity/DrawerNav.tsx
- package.json
- pages/activity/[id]/index.tsx
- pnpm-lock.yaml
> [refact] nav component

- components/Activity/Card.tsx
- components/Activity/Map.tsx
- models/Activity.ts
- models/Forum.ts
- models/Place.ts
- package.json
- pages/activity/[id]/agenda/[agendaId]/invitation.tsx
- pages/activity/[id]/index.tsx
- pnpm-lock.yaml
1. [add] Activity Map component & Place model (closes #145)
2. [optimize] Activity addresses support Lark Location objects
> [add] Activity Map component & Place model

- components/ListMap.tsx
> [optimize] Jump to Gaode Map

- components/Activity/Card.tsx
- components/Article/Card.tsx
- components/Issues/Card.tsx
- components/Issues/IssueModule.module.less
- components/Issues/IssueModule.tsx
- components/data.ts
- models/Activity/Forum.ts
- package.json
- pages/_document.tsx
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/agenda/[agendaId]/invitation.tsx
- pages/project/issues/index.tsx
- pnpm-lock.yaml
- styles/globals.less
1. [add] Issue Card component
2. [optimize] Issue Dashboard page (fix #147)
3. [optimize] Activity pages loading
> [add] Issue Card component

- components/Issues/IssueModule.tsx
- components/Member/Card.module.less
- models/Activity/Place.ts
- models/Activity/Staff.ts
- pages/activity/[id]/index.tsx
- pages/activity/[id]/volunteer.tsx
- pages/project/issues/index.tsx
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
> [fix] several UI bugs of Activity Volunteer & GitHub Issue pages

- models/Community/CommunityMember.ts
- models/Community/index.ts
- pages/community/[community].tsx
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
Checklist（清单）:
- Closes #177
- Closes #178
> [optimize] Only display member records whose approver information is not empty

- components/Activity/Card.tsx
- models/Activity/index.ts
- pages/activity/[id]/index.tsx
> [add] activity add alias path

- pages/activity/[id]/index.tsx
- pages/search/index.tsx
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
> [optimize]: add add previous activity Button

- components/Activity/Agenda/Toolbar.tsx
- components/Activity/CheckConfirm.tsx
- components/Base/UserMenu.tsx
- models/Activity/CheckEvent.ts
- models/Base/User.ts
- package.json
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/user/[uuid].tsx
- pnpm-lock.yaml
1. [add] User Profile page (close #195)
2. [optimize] replace Mobile Phone with User ID for Check Event
> [add] User Profile page

- README.md
- models/Repository.ts
- pages/project/index.tsx
- pages/project/issues/index.tsx
1. [optimize] reduce Call Count of GitHub API (fix #211)
2. [fix] CI/CD action badge
> [optimize] reduce Call Count of GitHub API

- components/Activity/Agenda/Card.tsx
> [fix] avatars undefined error

- docker-compose.yml
> feat: docker container autostart

- components/Activity/People.tsx
- models/Activity/Forum.ts
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/agenda/[agendaId]/invitation.tsx
- pages/activity/[id]/index.tsx
- pnpm-lock.yaml
1. 多维表格： forum 表格中添加 `producerOrganizations` 字段
2. 网站：如果字段不为空，则显示出品人职位及所属公司
1. 若字段不为空，显示出品人职位及所属公司
2. 页面头像大小统一（`5rem`)
3. 议程详情页多导师布局换行
若字段不为空，显示职位及所属公司
- Closes #230
- Closes #231
> feat: enhance profile display of producers and mentors

- pages/_app.tsx
> feat: google analytics

- docker-compose.yml
> feat: limit docker log size

- components/Activity/Agenda/Card.tsx
- components/Base/LarkImage.tsx
- components/Organization/Card.tsx
- models/Activity/Forum.ts
- models/Product/Article.ts
- package.json
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/agenda/[agendaId]/invitation.tsx
- pages/activity/[id]/index.tsx
- pages/article/[id]/index.tsx
- pages/member/[name].tsx
- pnpm-lock.yaml
1. [add] Original Link of Article Detail page (closes #227)
2. [fix] Fallback loop of Lark Image component
3. [optimize] Empty Safety of Text Color fields (fix #245)
4. [optimize] update Upstream packages
> [add] Original Link of Article Detail page

- components/Layout/MainNav.tsx
> fix: nav bar dropdown list title display

- components/Base/VerticalScrollableBox/index.tsx
- pages/activity/[id]/index.tsx
> fix: VerticalScrollable miss scrollItem

- Dockerfile
> [optimize] Docker image size

- components/Activity/Agenda/Card.tsx
- components/Activity/Card.tsx
- components/Activity/GiftCard.module.less
- components/Activity/GiftCard.tsx
- components/Article/Card.tsx
- components/Community/CommunityCard.tsx
- components/Community/MemberCard.tsx
- components/Election/ElectorCard.tsx
- components/Git/Card.tsx
- components/Issues/IssueModule.tsx
- components/Map/ListMap.tsx
- components/Member/Card.module.less
- components/Organization/Card.tsx
- pages/department/[name].tsx
- styles/globals.less
1. [optimize] Long List render performance (fix #273)
2. [add] Pointer Cursor CSS utility
> [optimize] Long List render performance

- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- package.json
- pages/_app.tsx
- pages/_document.tsx
- pnpm-lock.yaml
1. [add] XiaoYuan Chat Bot based on AI Table (closes #189)
2. [fix] UnPkg CDN blocked by GFW
3. [optimize] update Upstream packages
> [add] XiaoYuan Chat Bot based on AI Table

- components/Activity/Agenda/Card.tsx
- components/Activity/Agenda/Toolbar.tsx
- models/Activity/Agenda.ts
- models/Activity/Forum.ts
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/index.tsx
> feat: show location and url on agenda calendar

- Dockerfile
- components/Activity/Agenda/Card.tsx
- components/Base/TimeRange.tsx
- models/Activity/index.ts
- models/Product/Article.ts
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/community/pioneer.tsx
- pages/user/[uuid].tsx
1. [add] Time Range component
2. [fix] some SSR detail errors
3. [fix] Sentry SSL error in Docker  (fix #283)
> [add] Time Range component

- docker-compose.yml
> feat: limit container use mem

- Dockerfile
> feat: use libjemalloc

- Dockerfile
Checklist（清单）:
- Closes #290
- Closes #293
> feat: GC config

- components/data.ts
- pages/meeting-calendar/index.tsx
- pages/public-meeting/index.tsx
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
> [optimize] add meeting calendar page

- components/Election/ElectorCard.tsx
- package.json
- pages/election/[year]/index.tsx
- pnpm-lock.yaml
1. [optimize] hide Vote counts in Election period
2. [optimize] update Upstream packages
> [optimize] hide Vote counts in Election period

- ReadMe.md
- themes/Electron/layout/component/calendar.ejs
- themes/Electron/layout/component/marker_map.ejs
- themes/Electron/layout/layout.ejs
1. [migrate] replace JSDelivr CDN with WebCache.cn
2. [add] global Migration Alert bar (closes #299)
> [migrate] replace JSDelivr CDN with WebCache.cn

- .github/workflows/deploy-production.yml
> build: change scp github action

- .github/workflows/deploy-production.yml
> build: update docker github action

- Dockerfile
- next.config.mjs
> use standalone to deduce docker image size

- Dockerfile
Checklist（清单）:
Closes #XXXXX
github actcion 报错 
```text
1 warning found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 25)
```
> fix github action warn

- components/Activity/Agenda/Card.tsx
- components/Activity/People.tsx
- models/Activity/Agenda.ts
- package.json
- pages/activity/[id]/agenda/[agendaId]/index.tsx
- pages/activity/[id]/agenda/[agendaId]/invitation.tsx
- pages/activity/[id]/index.tsx
- pnpm-lock.yaml
[![PR-355](https://badgen.net/badge/GitHub.dev/PR-355/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/kaiyuanshe.github.io/pull/355) [![PR-355](https://badgen.net/badge/GitHub%20codespaces/PR-355/black?icon=github)](https://codespaces.new/kaiyuanshe/kaiyuanshe.github.io/pull/355) [![PR-355](https://badgen.net/badge/GitPod.io/PR-355/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/355) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
1. [optimize] Page Navigator expansion of Activity Home page (resolve #354)
2. …
> [optimize] Page Navigator expansion of Activity Home page

- components/Issue/Card.tsx
- components/Proposal/Card.tsx
- models/Governance/Issue.ts
- models/Governance/Proposal.ts
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
[![PR-371](https://badgen.net/badge/GitHub.dev/PR-371/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/kaiyuanshe.github.io/pull/371) [![PR-371](https://badgen.net/badge/GitHub%20codespaces/PR-371/black?icon=github)](https://codespaces.new/kaiyuanshe/kaiyuanshe.github.io/pull/371) [![PR-371](https://badgen.net/badge/GitPod.io/PR-371/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/371) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
Checklist（清单）:
Closes #329
Closes #330
> 意见箱  提案库显示更多信息

- .gitignore
- pages/_document.tsx
[![PR-385](https://badgen.net/badge/GitHub.dev/PR-385/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/kaiyuanshe.github.io/pull/385) [![PR-385](https://badgen.net/badge/GitHub%20codespaces/PR-385/black?icon=github)](https://codespaces.new/kaiyuanshe/kaiyuanshe.github.io/pull/385) [![PR-385](https://badgen.net/badge/GitPod.io/PR-385/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/385) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
Checklist（清单）:
Closes #XXXXX
> add npmrc to  .gitignore

- .gitmodules
- components/data.ts
- package.json
- pages/_app.tsx
- pages/article/original-index.tsx
- pnpm-lock.yaml
- translation/en-US.ts
- translation/zh-CN.ts
- translation/zh-TW.ts
- utility/MDX.ts
[![PR-389](https://badgen.net/badge/GitHub.dev/PR-389/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/kaiyuanshe.github.io/pull/389) [![PR-389](https://badgen.net/badge/GitHub%20codespaces/PR-389/black?icon=github)](https://codespaces.new/kaiyuanshe/kaiyuanshe.github.io/pull/389) [![PR-389](https://badgen.net/badge/GitPod.io/PR-389/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/389) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
fix #42
> [add] Archived articles in KYS OWS 2019 based on Async MDX walker

- .github/workflows/deploy-production.yml
[![PR-390](https://badgen.net/badge/GitHub.dev/PR-390/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/kaiyuanshe.github.io/pull/390) [![PR-390](https://badgen.net/badge/GitHub%20codespaces/PR-390/black?icon=github)](https://codespaces.new/kaiyuanshe/kaiyuanshe.github.io/pull/390) [![PR-390](https://badgen.net/badge/GitPod.io/PR-390/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/390) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
Checklist（清单）:
Closes #XXXXX
> feat: use gha cache 
